<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Modgud.TestApps.ResourceApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modgud.Client.AspNetCore\Modgud.Client.AspNetCore.csproj" />
  </ItemGroup>

</Project>
