<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoar.Auth.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoar.Auth.Authorization\Cocoar.Auth.Authorization.csproj" />
  </ItemGroup>

</Project>
