<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TimeToDo.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeToDo.Authorization\TimeToDo.Authorization.csproj" />
  </ItemGroup>

</Project>
