<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Modgud.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Modgud.Tests.Unit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="Riok.Mapperly" />
    <PackageReference Include="WolverineFx.Marten" />
    <PackageReference Include="Marten" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modgud.Domain\Modgud.Domain.csproj" />
    <ProjectReference Include="..\Modgud.Authorization\Modgud.Authorization.csproj" />
    <ProjectReference Include="..\Common\BuildingBlocks.EventDispatcher\BuildingBlocks.EventDispatcher.csproj" />
    <ProjectReference Include="..\Common\BuildingBlocks.Helper\BuildingBlocks.Helper.csproj" />
  </ItemGroup>

</Project>
