<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoar.Auth.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cocoar.Configuration.Abstractions" />
    <PackageReference Include="Cocoar.Configuration.Secrets.Abstractions" />
    <PackageReference Include="Marten" />
    <PackageReference Include="Weasel.Core" />
    <PackageReference Include="UAParser" />
    <PackageReference Include="Fido2" />
    <!-- OpenIddict (using custom Marten stores, no EF Core) -->
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="OpenIddict" />
    <PackageReference Include="OpenIddict.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoar.Auth.Application\Cocoar.Auth.Application.csproj" />
  </ItemGroup>

</Project>
