<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Cocoar.Auth.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Weasel.Core" />
    <PackageReference Include="UAParser" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoar.Auth.Application\Cocoar.Auth.Application.csproj" />
  </ItemGroup>

</Project>
